=== PerettoLucas/3-4-5-TFO-INFO/XMLEinfuehrung/src/XML/party.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.tfobz.net/partySchema"
	targetNamespace="http://www.tfobz.net/partySchema" 
	elementFormDefault="qualified">

	<xsd:element name="party" type="partyType"/>
	
	<xsd:complexType name="partyType">
		<xsd:sequence>
			<xsd:element name="gast" type="gastType" minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="waechter" type="waechterType" minOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="datum" type="datumType" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="gastType">
		<xsd:sequence>
			<xsd:element name="getraenk" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
			<xsd:element name="zustand" type="zustandType" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="waechterType">
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>

	<xsd:simpleType name="datumType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-3][0-9].[0-1][0-9].[0-9][0-9]" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="zustandType">
		<xsd:complexContent>
			<xsd:restriction base="xsd:anyType">
				<xsd:attribute name="nuechtern" type="xsd:boolean" />
				<xsd:attribute name="ledig" type="xsd:boolean" />
			</xsd:restriction>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>

=== PerettoLucas/3-4-5-TFO-INFO/XMLEinfuehrung/src/net/tfobz/rssreader/party.xml
<?xml version="1.0" encoding="UTF-8"?>
<pty:party xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tfobz.net/partySchema party.xsd"
	xmlns:pty="http://www.tfobz.net/partySchema"
	datum="31.12.14">
    <pty:gast name="Albert Angsthase">
        <pty:getraenk>
     		Wein
        </pty:getraenk>
        <pty:getraenk>
            Bier
        </pty:getraenk>
        <pty:zustand ledig="true" nuechtern="false"/>
    </pty:gast>
    <pty:gast name="Elsa Ehrlich">
        <pty:getraenk>
            Milch
        </pty:getraenk>
        <pty:zustand ledig="true" nuechtern="true"/>
    </pty:gast>
    <pty:waechter name="Schorsch Schrecklich"/>
</pty:party>

=== PerettoLucas/3-4-5-TFO-INFO/XMLEinfuehrung/src/XML/partyWithXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<pty:party xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tfobz.net/partySchema party.xsd"
	xmlns:pty="http://www.tfobz.net/partySchema"
	datum="31.12.14">
    
    <pty:gast name="Daniel GÃ¶zz">
    	<pty:getraenk>
    		Saftele
    	</pty:getraenk>
    	<pty:zustand nuechtern="false" ledig="true"/>
    </pty:gast>
    
    <pty:gast name="Xalenander Soini">
    	<pty:getraenk>
    		Tee
    	</pty:getraenk>
    	<pty:zustand nuechtern="true" ledig="false"/>
    </pty:gast>
    
   	<pty:waechter name="Schorsch Schrecklich"/>
   	
</pty:party>
