=== PerettoLucas/3-4-5-TFO-INFO/XMLEinfuehrung/src/XML/party.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT party (gast+, waechter+)>
<!ATTLIST party datum CDATA #REQUIRED>
<!ELEMENT gast (getraenk*, zustand)>
<!ATTLIST gast name CDATA #REQUIRED>
<!ELEMENT waechter EMPTY>
<!ATTLIST waechter name CDATA #REQUIRED>
<!ELEMENT getraenk (#PCDATA)>
<!ELEMENT zustand EMPTY>
<!ATTLIST zustand ledig CDATA #IMPLIED nuechtern CDATA #IMPLIED>

=== PerettoLucas/3-4-5-TFO-INFO/XMLEinfuehrung/src/XML/partyWithDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE party SYSTEM "party.dtd">
<party datum="31.12.14" >
    <gast name="Albert Angsthase">
        <getraenk>
            Wein
        </getraenk>
        <getraenk>
            Bier
        </getraenk>
        <zustand ledig="true" nuechtern="false"/>
    </gast>
    <gast name="Elsa Ehrlich">
        <getraenk>
            Apfelsaft
        </getraenk>
        <zustand ledig="true" nuechtern="true"/>
    </gast>
	<waechter name="Schorsch Schrecklich"/>
</party>
